// sampleData.js
const sampleData = {
    // 1. Roles
    roles: [
        {
            id: 1,
            roleName: "Admin",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 2,
            roleName: "Customer",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 3,
            roleName: "Staff",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 2. Users
    users: [
        {
            id: 1,
            userName: "Nguyễn Văn An",
            gender: true,
            email: "an.nguyen@example.com",
            passwordHash: "hashed_password_1",
            phoneNumber: "0901234567",
            userAddress: "123 Đường Láng, Đống Đa, Hà Nội",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            roleId: 1,
        },
        {
            id: 2,
            userName: "Trần Thị Bình",
            gender: false,
            email: "binh.tran@example.com",
            passwordHash: "hashed_password_2",
            phoneNumber: "0912345678",
            userAddress: "456 Lê Lợi, TP.HCM",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: " spateSystem",
            updatedBy: "System",
            roleId: 2,
        },
        {
            id: 3,
            userName: "Lê Minh Châu",
            gender: true,
            email: "chau.le@example.com",
            passwordHash: "hashed_password_3",
            phoneNumber: "0923456789",
            userAddress: "789 Nguyễn Huệ, Đà Nẵng",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            roleId: 3,
        },
    ],

    // 3. News
    news: [
        {
            id: 1,
            title: "Xu hướng nội thất 2025",
            content: "Bài viết về các xu hướng thiết kế nội thất hiện đại năm 2025...",
            newsAvatar: "news1.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            userId: 1,
        },
        {
            id: 2,
            title: "Mẹo chọn sofa cho phòng khách",
            content: "Hướng dẫn chi tiết cách chọn sofa phù hợp với không gian...",
            newsAvatar: "news2.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            userId: 1,
        },
    ],

    // 4. Categories
    categories: [
        {
            id: 1,
            categoryName: "Sofa",
            descriptions: "Các loại sofa hiện đại và cổ điển",
            imageURL: "sofa_category.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 2,
            categoryName: "Bàn ăn",
            descriptions: "Bàn ăn cho gia đình và nhà hàng",
            imageURL: "dining_table_category.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 3,
            categoryName: "Giường ngủ",
            descriptions: "Giường ngủ đa phong cách",
            imageURL: "bed_category.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 5. Colors
    colors: [
        {
            id: 1,
            colorName: "Xám",
            imageURL: "grey.jpg",
            colorCode: "#808080",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 2,
            colorName: "Nâu",
            imageURL: "brown.jpg",
            colorCode: "#8B4513",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 3,
            colorName: "Trắng",
            imageURL: "white.jpg",
            colorCode: "#FFFFFF",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 6. Sizes
    sizes: [
        {
            id: 1,
            sizeName: "Nhỏ",
            imageURL: "small_size.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 2,
            sizeName: "Trung",
            imageURL: "medium_size.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 3,
            sizeName: "Lớn",
            imageURL: "large_size.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 7. Materials
    materials: [
        {
            id: 1,
            materialName: "Gỗ tự nhiên",
            imageURL: "natural_wood.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 2,
            materialName: "Vải nỉ",
            imageURL: "velvet_fabric.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 3,
            materialName: "Da thật",
            imageURL: "genuine_leather.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 8. Brands
    brands: [
        {
            id: 1,
            brandName: "JYSK",
            imageURL: "jysk_logo.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 2,
            brandName: "IKEA",
            imageURL: "ikea_logo.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 3,
            brandName: "HOANG ANH GIA LAI",
            imageURL: "hagl_logo.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 9. Countries
    countries: [
        {
            id: 1,
            countryName: "Việt Nam",
            imageURL: "vn_flag.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 2,
            countryName: "Thụy Điển",
            imageURL: "sweden_flag.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 3,
            countryName: "Đan Mạch",
            imageURL: "denmark_flag.jpg",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 10. Units
    units: [
        {
            id: 1,
            unitName: "Cái",
            description: "Đơn vị tính cho sản phẩm nội thất",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 2,
            unitName: "Bộ",
            description: "Đơn vị tính cho bộ sản phẩm",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 11. Suppliers
    suppliers: [
        {
            id: 1,
            supplierName: "Công ty Nội thất Minh Anh",
            contactName: "Trần Văn Minh",
            email: "minhanh@example.com",
            phoneNumber: "0931234567",
            imageURL: "minhanh_logo.jpg",
            notes: "Chuyên cung cấp sofa và bàn ăn",
            taxID: "123456789",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 2,
            supplierName: "Công ty Gỗ HAGL",
            contactName: "Nguyễn Thị Hoa",
            email: "hagl@example.com",
            phoneNumber: "0942345678",
            imageURL: "hagl_logo.jpg",
            notes: "Chuyên cung cấp gỗ tự nhiên",
            taxID: "987654321",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 12. Products
    products: [
        {
            id: 1,
            productName: "Sofa góc L",
            specificationDescription: "Sofa góc L hiện đại, phù hợp phòng khách 20m2",
            viewCount: 100,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            brandId: 1,
            categoryId: 1,
            countriesId: 2,
            supplierId: 1,
        },
        {
            id: 2,
            productName: "Bàn ăn gỗ sồi",
            specificationDescription: "Bàn ăn 6 ghế, gỗ sồi tự nhiên",
            viewCount: 50,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            brandId: 2,
            categoryId: 2,
            countriesId: 1,
            supplierId: 2,
        },
        {
            id: 3,
            productName: "Giường ngủ 1.8m",
            specificationDescription: "Giường ngủ hiện đại, khung gỗ tự nhiên",
            viewCount: 75,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            brandId: 3,
            categoryId: 3,
            countriesId: 1,
            supplierId: 2,
        },
    ],

    // 13. ProductVariant
    productVariants: [
        {
            id: 1,
            originalPrice: 15000000.0,
            discountedPrice: 13500000.0,
            stockQty: 10,
            imageURL: "sofa_goc_xam.jpg",
            productId: 1,
            colorId: 1,
            sizeId: 3,
            materialId: 2,
            unitId: 1,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 2,
            originalPrice: 8000000.0,
            discountedPrice: null,
            stockQty: 15,
            imageURL: "ban_an_go.jpg",
            productId: 2,
            colorId: 2,
            sizeId: 2,
            materialId: 1,
            unitId: 1,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 3,
            originalPrice: 12000000.0,
            discountedPrice: 10800000.0,
            stockQty: 5,
            imageURL: "giuong_ngu_trang.jpg",
            productId: 3,
            colorId: 3,
            sizeId: 3,
            materialId: 1,
            unitId: 1,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 14. StoreInformation
    storeInformation: [
        {
            id: 1,
            storeName: "TOM Furniture",
            storeAddress: "123 Nguyễn Trãi, Thanh Xuân, Hà Nội",
            logo: "tom_logo.jpg",
            phoneNumber: "0901234567",
            email: "contact@tomfurniture.com",
            linkWebsite: "https://tomfurniture.com",
            latitude: 21.017123,
            longitude: 105.812345,
            ownerName: "Nguyễn Văn Tôm",
            businessType: "Bán lẻ nội thất",
            operatingHours: "8:00 - 20:00",
            storeDescription: "Cửa hàng nội thất hiện đại",
            establishmentDate: "2020-01-01",
            taxId: "1234567890",
            branchCode: "HN01",
            linkSocialFacebook: "https://facebook.com/tomfurniture",
            linkSocialTwitter: "https://twitter.com/tomfurniture",
            linkSocialInstagram: "https://instagram.com/tomfurniture",
            linkSocialTiktok: "https://tiktok.com/tomfurniture",
            linkSocialYoutube: "https://youtube.com/tomfurniture",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 15. Banners
    banners: [
        {
            id: 1,
            title: "Khuyến mãi mùa thu",
            description: "Giảm giá 20% cho sofa",
            imageURL: "banner_sofa.jpg",
            linkURL: "https://tomfurniture.com/sale",
            startDate: new Date().toISOString(),
            endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            displayOrder: 1,
            position: "Top",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            userId: 1,
        },
    ],

    // 16. Sliders
    sliders: [
        {
            id: 1,
            title: "Sofa mới 2025",
            description: "Sofa góc L hiện đại",
            imageURL: "slider_sofa.jpg",
            linkURL: "https://tomfurniture.com/sofa",
            startDate: new Date().toISOString(),
            endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            isPoster: false,
            position: "Home",
            displayOrder: 1,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            productId: 1,
        },
    ],

    // 17. ProductReviews
    productReviews: [
        {
            id: 1,
            starRating: 5,
            content: "Sofa rất đẹp, chất lượng tốt!",
            relatedVideo: null,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            userId: 2,
            proId: 1,
        },
        {
            id: 2,
            starRating: 4,
            content: "Bàn ăn chắc chắn, giao hàng nhanh",
            relatedVideo: null,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            userId: 2,
            proId: 2,
        },
    ],

    // 18. ImageProductReviews
    imageProductReviews: [
        {
            id: 1,
            imageURL: "sofa_review1.jpg",
            attribute: "Hình ảnh sofa góc L",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            productReviewId: 1,
        },
    ],

    // 19. Comment
    comments: [
        {
            id: 1,
            likeCount: 10,
            content: "Đồng ý, sofa này rất đẹp!",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            proReviewId: 1,
            userId: 2,
        },
    ],

    // 20. PaymentMethods
    paymentMethods: [
        {
            id: 1,
            namePaymentMethod: "Tiền mặt",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 2,
            namePaymentMethod: "Chuyển khoản",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 3,
            namePaymentMethod: "Thẻ tín dụng",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 21. OrderAddress
    orderAddresses: [
        {
            id: 1,
            recipient: "Trần Thị Bình",
            phoneNumber: "0912345678",
            addressDetailRecipient: "456 Lê Lợi",
            city: "TP.HCM",
            district: "Quận 1",
            ward: "Phường Bến Nghé",
            isDeafaultAddress: true,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            userId: 2,
        },
    ],

    // 22. OrderStatus
    orderStatuses: [
        {
            id: 1,
            orderStatusName: "Chờ xác nhận",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 2,
            orderStatusName: "Đang giao",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 3,
            orderStatusName: "Đã giao",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 23. PromotionTypes
    promotionTypes: [
        {
            id: 1,
            promotionTypeName: "Giảm giá phần trăm",
            description: "Giảm giá theo phần trăm",
            promotionUnit: 1,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
        {
            id: 2,
            promotionTypeName: "Giảm giá cố định",
            description: "Giảm giá số tiền cố định",
            promotionUnit: 0,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
        },
    ],

    // 24. Promotions
    promotions: [
        {
            id: 1,
            promotionCode: "SALE20",
            discountValue: 20.0,
            orderMinimum: 1000000.0,
            maximumDiscountAmount: 5000000.0,
            startDate: new Date().toISOString(),
            endDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
            couponUsage: 100,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            promotionTypeId: 1,
        },
    ],

    // 25. Shipping
    shipping: [
        {
            id: 1,
            city: "TP.HCM",
            district: "Quận 1",
            ward: "Phường Bến Nghé",
            shippingPrice: 50000.0,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            userId: 2,
        },
    ],

    // 26. Orders
    orders: [
        {
            id: 1,
            orderDate: new Date().toISOString(),
            total: 13500000.0,
            priceDiscount: 1500000.0,
            shippingPrice: 50000.0,
            isPaid: false,
            note: "Giao hàng cẩn thận",
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            userId: 2,
            orderAddId: 1,
            orderStaId: 1,
            paymentMethodId: 1,
            promotionId: 1,
        },
    ],

    // 27. OrderDetails
    orderDetails: [
        {
            id: 1,
            quantity: 1,
            price: 13500000.0,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            proVarId: 1,
            orderId: 1,
        },
    ],

    // 28. Cart
    cart: [
        {
            id: 1,
            quantity: 2,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            proVarId: 1,
            userId: 2,
        },
    ],

    // 29. Feedbacks
    feedbacks: [
        {
            id: 1,
            message: "Sản phẩm rất đẹp, giao hàng nhanh!",
            parentFeedbackId: null,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            userId: 2,
        },
        {
            id: 2,
            message: "Cảm ơn bạn đã phản hồi!",
            parentFeedbackId: 1,
            isActive: true,
            createdDate: new Date().toISOString(),
            updatedDate: new Date().toISOString(),
            createdBy: "System",
            updatedBy: "System",
            userId: 1,
        },
    ],
};

export default sampleData;
